name: Deploy AWS Lambda

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
    paths-ignore:
      - README.md  # Ignores changes to README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
    types: [opened, synchronize, reopened]
    # Prevent workflow from running on Dependabot PRs
    # We'll use a job-level if condition below
jobs:
  deploy:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --target package boto3

      - name: Package Lambda Function
        run: |
          cd package
          zip -r ../lambda_function.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to AWS Lambda using AWS CLI
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda_function.zip


          ###